server:
  port: 5000

spring:
  datasource:
    url: jdbc:h2:file:./tiny
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false

cron: # every 15 minutes
  expression: "0 0/15 * * * *"
